### ISSUE TITLE
Support for TCP Syslog

### ISSUE THREAD

**Issue by Alan-Carr** [trparky/Free-SysLog#11] opened 2024-09-02 10:42 UTC
I believe that this application only supports UDP Syslog it would be useful if it also supported TCP

**Comment by trparky** [comment] 2024-09-02 15:29
I've implemented preliminary and very experimental code to receive syslog data via TCP. You're welcome to try it but be warned, it's still very experimental and may be buggy. I have no way to test the new code since everything I have uses UDP for syslog data.

Below is a compiled version that supports TCP. Note, UDP is still the preferred method for receiving syslog data.

**Comment by trparky** [comment] 2024-09-02 15:47
Here's an updated ZIP file, I forgot to start the server in the prior compiled version.
[Free SysLog.zip](https://github.com/user-attachments/files/16839474/Free.SysLog.zip)

**Comment by trparky** [comment] 2024-09-03 03:18
I setup a rudimentary test environment in which I simulated sending data to the TCP server and fixed a lot of bugs. I have a new binary for you to test. However, you will need to enable the TCP server in the Settings menu to turn the TCP server on. I'm sure you will find the item in the Settings menu, it's rather self-explanatory.
[Free SysLog.zip](https://github.com/user-attachments/files/16843020/Free.SysLog.zip)

**Comment by Alan-Carr** [comment] 2024-09-03 07:44
Hi

I have carried out some basic tests with your latest Version 3.1 Build 3 (Debug Build) 

I noticed initially when I hadn't set enable syslog server that a TCP port was open from your application to a 172.x  address maybe this is a result of some of your debug code ?

I am getting syslog data over TCP into your application however the data we are monitoring contains structured data as specified in rfc 5424

**Comment by Alan-Carr** [comment] 2024-09-03 08:52
One additional thing I have noticed it seem difficult to drag the application to an additional monitor screen

**Comment by trparky** [comment] 2024-09-03 15:02
> this is a result of some of your debug code ?
> 
> I am getting syslog data over TCP into your application however the data we are monitoring contains structured data as specified in rfc 5424

Yeah, I fixed a bug regarding that. See... https://github.com/trparky/Free-SysLog/commit/8c1c2f7b396fdfe6ef4fb7b3c3593c97701e99dd

**Comment by trparky** [comment] 2024-09-03 15:09
> One additional thing I have noticed it seem difficult to drag the application to an additional monitor screen

Yes, I've noticed that as well. I have a fix in place.

**Comment by Alan-Carr** [comment] 2024-09-03 15:21
Thanks for the update, seems like great progress

Do you think you maybe able to incorporate the structured data ?

**Comment by trparky** [comment] 2024-09-03 15:23
> Thanks for the update, seems like great progress
> 
> Do you think you maybe able to incorporate the structured data ?

Excuse me? I'm not sure I understand.

Here's a new program binary to test.
[Free SysLog.zip](https://github.com/user-attachments/files/16851039/Free.SysLog.zip)

**Comment by Alan-Carr** [comment] 2024-09-03 15:42
With ref to the structured data see https://datatracker.ietf.org/doc/html/rfc5424#section-6  and https://datatracker.ietf.org/doc/html/rfc5424#section-6.5

**Comment by trparky** [comment] 2024-09-03 22:25
OK, it took a lot of time to do it but it's done. I think.
[Free SysLog.zip](https://github.com/user-attachments/files/16857758/Free.SysLog.zip)

**Comment by Alan-Carr** [comment] 2024-09-04 12:24
Hi

Thanks for the update and its great to see such progress. The data we are monitoring contains structured data within the Log message incl for example a timestamp which amongst others I'm expecting to see in separate columns. 

We are also seeing on some occasions  where multiple messages are shown in a single line eg the Log column shows more than one message.

Copying log text doesn't appear to work as expected

**Comment by trparky** [comment] 2024-09-04 14:07
> We are also seeing on some occasions where multiple messages are shown in a single line eg the Log column shows more than one message.

I've noticed that as well with some of my networking equipment. As for why, I'm not sure. All the code is doing is literally taking in what it's being fed, parsing it, displaying it; nothing more, nothing less. What I'm saying is that if there are duplicate log entries, it's the system that's sending it that's duplicating the data.
> Copying log text doesn't appear to work as expected

OK, I'll work on that bug later. Right now, we're working with alpha code, not even beta level code here. In other words, expect bugs.

**Comment by Alan-Carr** [comment] 2024-09-04 14:18
Its not duplicate messages its multiple different messages on the same line.  Bearing in mind that the log message content also contains timestamp with milliseconds resolution and additional data which should be in columns

**Comment by trparky** [comment] 2024-09-04 14:21
Are you saying that the line breaks aren't being handled properly? As for timestamps, the program is generating them on the fly as the log comes in. Now, I could make additional changes to use the timestamp that the log comes in with instead of generating them in the program itself.

**Comment by Alan-Carr** [comment] 2024-09-04 14:31
I think you should keep your timestamp and show the timestamp that is part of the additional structured data in the log messages along with an other additional columns.

**Comment by Alan-Carr** [comment] 2024-09-04 14:32
keep yours as received time

**Comment by Alan-Carr** [comment] 2024-09-04 14:34
you might get multiple separate messages at the same timestamp second

**Comment by Alan-Carr** [comment] 2024-09-04 14:38
Just seeing if I can reply directly


Alan CARR - Senior QC Engineer
T. +441182286646 ***@***.******@***.***>

EVS Broadcast Equipment - Building B, Crowthorne House Nine Mile Ride - RG40 3GA Berkshire - UNITED KINGDOM


Quicklinks:   Latest News<https://evs.com/company/news?utm_source=Outlook&utm_medium=email&utm_campaign=staff+signature>   Next Events<https://evs.com/company/events?utm_source=Outlook&utm_medium=email&utm_campaign=staff+signature>   Contacts<https://evs.com/contact?utm_source=Outlook&utm_medium=email&utm_campaign=staff+signature>
Community:   Facebook<http://www.facebook.com/home.php#!/pages/EVS-Broadcast-Equipment/262186759015?ref=ts>   Twitter<http://twitter.com/EVSEquipment>    LinkedIn<https://www.linkedin.com/company/evs-broadcast-equipment>  Youtube<http://www.youtube.com/user/EVSBroadcast>   Instagram<http://instagram.com/evsequipment>   MyEVS<https://viaportal.evs.com/?utm_source=Outlook&utm_medium=email&utm_campaign=staff+signature>   RSS<http://www.evs.com/rss/news>

<https://evs.com/company/news/evs-ibc-2023?utm_source=Outlook+signature&utm_medium=email&utm_campaign=IBC2023><https://evs.com/company/events/adding-ai-to-your-creative-toolbox?utm_source=Outlook+signature&utm_medium=email&utm_campaign=InsideOut6><https://evs.com/company/events/adding-ai-to-your-creative-toolbox?utm_source=Outlook+signature&utm_medium=email&utm_campaign=InsideOut6><https://evs.com/happy-2024?utm_source=Outlook+signature&utm_medium=email&utm_campaign=EOYgreetings2024><https://evs.com/products/live-replays-storytelling/xtramotion?utm_source=Outlook&utm_medium=email&utm_campaign=Product+spotlight+signature><https://evs.com/notareplay>[cid:evsatibc2024-email-signature_9b30da2a-074f-4971-9b55-40b54fb5e849.gif]<https://evs.com/company/events/ibc-2024?utm_source=staff+signature&utm_medium=email&utm_campaign=IBC2024>

www.evs.com<http://www.evs.com>


EVS Broadcast Equipment is a commercial name which is used for all legal entities of our group<https://evs.com/sites/default/files/evs_broadcast_equipment_addresses.pdf>.

At EVS we give utmost importance to your data's privacy. If you wish to know more on how we manage your data and on your rights, please consult our Privacy Statement<https://evs.com/en/privacystatement>.

This message may contain confidential information and is intended solely for the use of the addressee. Please do not use or publish the contained information without the agreement of the sender. If you are not the intended recipient of this message, please notify the sender and do not disclose, use, disseminate or copy this message.

Please consider the environment before printing this email.

**Comment by trparky** [comment] 2024-09-04 23:46
I'll continue to work on this on the weekend when I have more free time to do this.

**Comment by trparky** [comment] 2024-09-05 00:53
I have, however, fixed the clipboard functionality since that was easy to fix.
[Free SysLog.zip](https://github.com/user-attachments/files/16882448/Free.SysLog.zip)

**Comment by trparky** [comment] 2024-09-06 23:00
Alright, I have a lot of changes in store for you. Hopefully they live up to your expectations.
[Free SysLog.zip](https://github.com/user-attachments/files/16913565/Free.SysLog.zip)

**Comment by Alan-Carr** [comment] 2024-09-07 14:56
Had a quick look data  below shows in  log field -:
Object reference not set to an instance of an object. --    at Free_SysLog.SyslogParser.SyslogParser.ProcessIncomingLog(String strLogText, String strSourceIP) in C:\Users\trpar\OneDrive\My Visual Studio Projects\Projects\Free SysLog\Free SysLog\Support Code\Namespace Code\Syslog Parser.vb:line 176

**Comment by trparky** [comment] 2024-09-07 17:57
I'll look into it when I get back in front of my computer.

**Comment by trparky** [comment] 2024-09-07 20:28
I put in some additional checks to hopefully solve that issue.

[Free SysLog.zip](https://github.com/user-attachments/files/16919847/Free.SysLog.zip)

**Comment by trparky** [comment] 2024-09-08 12:33
OK, I was able to reproduce the bug that you mentioned on my system but I'm still trying to track down why the bug is happening. I put some additional debug code into the program so as to capture data so hopefully the next time it happens, I'll have additional data to work with.

**Comment by Alan-Carr** [comment] 2024-09-09 07:42
Using your latest -:

Object reference not set to an instance of an object. --    at Free_SysLog.SyslogParser.SyslogParser.ConvertLineFeeds(String strInput) in C:\Users\trpar\OneDrive\My Visual Studio Projects\Projects\Free SysLog\Free SysLog\Support Code\Namespace Code\Syslog Parser.vb:line 122
   at Free_SysLog.SyslogParser.SyslogParser.ProcessIncomingLog(String strRawLogText, String strSourceIP) in C:\Users\trpar\OneDrive\My Visual Studio Projects\Projects\Free SysLog\Free SysLog\Support Code\Namespace Code\Syslog Parser.vb:line 183

**Comment by trparky** [comment] 2024-09-09 15:14
I refactored a lot of code and quite possibly fixed the bug in the process. I think.
[Free SysLog.zip](https://github.com/user-attachments/files/16932580/Free.SysLog.zip)

**Comment by trparky** [comment] 2024-09-09 15:31
Nevermind the previous file, here's another; I refactored more code for easier maintenance.
[Free SysLog.zip](https://github.com/user-attachments/files/16932790/Free.SysLog.zip)

**Comment by trparky** [comment] 2024-09-10 23:32
**AH HA! Found it! I found the bug!**

The bug has to do with how my regexp pattern used to parse syslog entries fails to parse logs if the remote app (or binary) that sent the log contains a space. I've tweaked the pattern to fix it.
[Free SysLog.zip](https://github.com/user-attachments/files/16956002/Free.SysLog.zip)

**Comment by Alan-Carr** [comment] 2024-09-11 15:58
Using your latest, I'm now getting a column for the timestamp sent from the syslog device. 

I'm seeing the syslog data in the log field however I'm still seeing vb error messages
 
Object reference not set to an instance of an object. --    at Free_SysLog.SyslogParser.SyslogParser.ConvertLineFeeds(String strInput) in C:\Users\trpar\OneDrive\My Visual Studio Projects\Projects\Free SysLog\Free SysLog\Support Code\Namespace Code\Syslog Parser.vb:line 125
   at Free_SysLog.SyslogParser.SyslogParser.ProcessIncomingLog(String strRawLogText, String strSourceIP) in C:\Users\trpar\OneDrive\My Visual Studio Projects\Projects\Free SysLog\Free SysLog\Support Code\Namespace Code\Syslog Parser.vb:line 175

**Comment by trparky** [comment] 2024-09-12 01:19
Damn, and here I thought I finally solved the issue. I guess I have more looking into this.

**Comment by trparky** [comment] 2024-09-12 01:25
I have to wonder if it has something to do with multiline log entries.

**Comment by trparky** [comment] 2024-09-12 01:36
Alright, I added some additional tweaks to the code.
[Free SysLog.zip](https://github.com/user-attachments/files/16972125/Free.SysLog.zip)

**Comment by trparky** [comment] 2024-09-12 22:13
More tweaks to the RegEx pattern. God I hate RegEx!
[Free SysLog.zip](https://github.com/user-attachments/files/16985917/Free.SysLog.zip)

**Comment by trparky** [comment] 2024-09-15 19:10
I'm closing this issue on account of the fact that I've not heard from you in over three days. I'm going to say that you're no longer interested in this program anymore. Feel free to re-open the issue or create a new issue if problems persist.

**Comment by Alan-Carr** [comment] 2024-09-16 07:35
@trparky 
I am still very much interested in your application and will test the latest

**Comment by Alan-Carr** [comment] 2024-09-16 08:53
@trparky 
I wasn't sure which version to test, I took the latest from GitHub

Unknown timestamp format. --    at Free_SysLog.SyslogParser.SyslogParser.ParseTimestamp(String timestamp) in C:\Users\trpar\OneDrive\My Visual Studio Projects\Projects\Free SysLog\Free SysLog\Support Code\Namespace Code\Syslog Parser.vb:line 119
   at Free_SysLog.SyslogParser.SyslogParser.AddToLogList(String strTimeStampFromServer, String strSourceIP, String strHostname, String strRemoteProcess, String strLogText, Boolean boolIgnored, Boolean boolAlerted, ValueTuple`2 priority, String strRawLogText) in C:\Users\trpar\OneDrive\My Visual Studio Projects\Projects\Free SysLog\Free SysLog\Support Code\Namespace Code\Syslog Parser.vb:line 224
   at Free_SysLog.SyslogParser.SyslogParser.ProcessIncomingLog(String strRawLogText, String strSourceIP) in C:\Users\trpar\OneDrive\My Visual Studio Projects\Projects\Free SysLog\Free SysLog\Support Code\Namespace Code\Syslog Parser.vb:line 193

**Comment by Alan-Carr** [comment] 2024-09-16 09:04
@trparky 
Screen shot showing server time -:

![10 02 30 16 09 2024](https://github.com/user-attachments/assets/cf21a7fb-cece-4617-aad5-6fdb1e6f27cb)

Time from log is in Milliseconds and it also seems that there is an hour offset from what is displayed compared with incoming

2024-09-16T09:58:03.290Z

**Comment by Alan-Carr** [comment] 2024-09-16 09:38
@trparky 
We get multiple messages in a single log.

From what I understand the "1269" below shows the length of the message.

1269 <134>1 2024-09-16T09:49:01.360Z

**Comment by trparky** [comment] 2024-09-17 14:09
OK, can you give me an example of a full log entry so that I can find out how the program parses the incoming log?

**Comment by trparky** [comment] 2024-09-17 14:17
> We get multiple messages in a single log.

That's weird. Because if I understand the syslog standard correctly, each log entry should be stand on its own. If there are multiple events, there should be multiple log entries.

**Comment by trparky** [comment] 2024-09-17 14:34
[Free SysLog.zip](https://github.com/user-attachments/files/17029905/Free.SysLog.zip)
OK, I included changes to the ParseTimestamp() function as per commit [98220d4](https://github.com/trparky/Free-SysLog/commit/98220d4d2724c182d15ac73079a27a673b5aab89).

**Comment by Alan-Carr** [comment] 2024-09-17 15:34
With your latest -:
Unknown timestamp format. --    at Free_SysLog.SyslogParser.SyslogParser.ParseTimestamp(String timestamp) in C:\Users\trpar\OneDrive\My Visual Studio Projects\Projects\Free SysLog\Free SysLog\Support Code\Namespace Code\Syslog Parser.vb:line 137
   at Free_SysLog.SyslogParser.SyslogParser.AddToLogList(String strTimeStampFromServer, String strSourceIP, String strHostname, String strRemoteProcess, String strLogText, Boolean boolIgnored, Boolean boolAlerted, ValueTuple`2 priority, String strRawLogText) in C:\Users\trpar\OneDrive\My Visual Studio Projects\Projects\Free SysLog\Free SysLog\Support Code\Namespace Code\Syslog Parser.vb:line 239
   at Free_SysLog.SyslogParser.SyslogParser.ProcessIncomingLog(String strRawLogText, String strSourceIP) in C:\Users\trpar\OneDrive\My Visual Studio Projects\Projects\Free SysLog\Free SysLog\Support Code\Namespace Code\Syslog Parser.vb:line 208

I note that the Server Timestamp shows only secs not msecs

**Comment by trparky** [comment] 2024-09-17 15:52
I threw the timestamp "2024-09-16T09:58:03.290Z" through my parser function and it returned 9/16/2024 9:58:03 AM. So, that's good. Right?

**Comment by trparky** [comment] 2024-09-17 15:55
If there's another timestamp that's failing, I need an example of it to test with.

**Comment by Alan-Carr** [comment] 2024-09-17 18:26
Regarding your comment about the timestamp

 "2024-09-16T09:58:03.290Z" through my parser function and it returned 9/16/2024 9:58:03 AM. So, that's good. Right?

The time is 09e:58.03.290 eg its in HH:MM:ss.SSS 
eg The time stamp ends in  290 Milliseconds eg 03 seconds and 290 Milliseconds

**Comment by trparky** [comment] 2024-09-17 18:49
> Regarding your comment about the timestamp
> 
> "2024-09-16T09:58:03.290Z" through my parser function and it returned 9/16/2024 9:58:03 AM. So, that's good. Right?
> 
> The time is 09e:58.03.290 eg its in HH:MM:ss.SSS eg The time stamp ends in 290 Milliseconds eg 03 seconds and 290 Milliseconds

OK, so again... Is the function parsing it is correctly?

**Comment by trparky** [comment] 2024-09-17 18:51
I just added some additional error handling of timestamps as per commit https://github.com/trparky/Free-SysLog/commit/9d104ce1c2fabd6732c967a2b8cadc872a871d52.
[Free SysLog.zip](https://github.com/user-attachments/files/17033609/Free.SysLog.zip)

**Comment by Alan-Carr** [comment] 2024-09-18 09:14
![image](https://github.com/user-attachments/assets/57a5fafc-7369-4b90-b8bd-f4c9e4093e6d)

With regards to the screenshot it seems that we are getting an extra message in the log "unable to parse timestamp" which is associated with the previous message. 

I note that the server time which comes from the message is only showing HH MM SS not ms

Furthermore I think the server time should only be seen in the server time column and no longer in the message but guess its no big deal if in both however the server time column needs to show the ms.

Bearing in mind you can get multiple separate messages on the same ms.

**Comment by trparky** [comment] 2024-09-18 13:50
Oh no, that helps! I now have something that I can use to develop a parser for the timestamp.

**Comment by trparky** [comment] 2024-09-18 14:05
OK, I got a new binary for you to test that includes two commits. https://github.com/trparky/Free-SysLog/commit/98220d4d2724c182d15ac73079a27a673b5aab89 and https://github.com/trparky/Free-SysLog/commit/9d104ce1c2fabd6732c967a2b8cadc872a871d52
[Free SysLog.zip](https://github.com/user-attachments/files/17045228/Free.SysLog.zip)

**Comment by trparky** [comment] 2024-09-18 14:06
Correction, these are the commits... https://github.com/trparky/Free-SysLog/commit/31028b8a3314a6793f058480a7d4962b2398ba80 and https://github.com/trparky/Free-SysLog/commit/6270c8a1eaea794e172c3a92e910db647c8921f5

**Comment by Alan-Carr** [comment] 2024-09-18 15:11
Whilst the server time column shows ms  hey remain at "000"
![15 53 47 18 09 2024](https://github.com/user-attachments/assets/d40ed9cc-e347-49ec-8fd4-baa92a40b1cd)

The log entries show multiple messages we can receive multiple messages with the same timestamp however I would expect these to be broken down into individual messages based on their length.

It seems that sometimes the next line in the grid is a continuation of the previous message such that the messages are not being broken down based on their timestamp and length.

In the screenshot below the "269" is missing a 1 which is probably on the previous message

![image](https://github.com/user-attachments/assets/749bc7a5-8474-4738-96ee-4c04debba829)

**Comment by Alan-Carr** [comment] 2024-09-18 15:35
If you use the menu item to stop server / start server it doesn't appear to stop the server and every start increases the number of ports that the application is using

**Comment by trparky** [comment] 2024-09-19 01:08
[Free SysLog.zip](https://github.com/user-attachments/files/17052043/Free.SysLog.zip)
OK, here's another test version.

**Comment by Alan-Carr** [comment] 2024-09-19 08:55
Looks like the splitting on Timestamps / length of message has been resolved and update of timecode field. I need to look further into the individual messages though.

**Comment by trparky** [comment] 2024-09-19 12:26
[Free SysLog.zip](https://github.com/user-attachments/files/17058997/Free.SysLog.zip)
I did some additional changes. Hopefully, I didn't break anything.

**Comment by Alan-Carr** [comment] 2024-09-19 13:37
I'll take a look at the latest, I need to check if the structured data is intact. Did you look at the way the server stop / start worked ? such that you don't get multiple ports open.

I also need to look at the export and archiving / deletion

**Comment by Alan-Carr** [comment] 2024-09-19 17:54
I think you may have broken it appears to be back to multiple messages in one line

**Comment by trparky** [comment] 2024-09-19 23:30
OK, that's been fixed.
[Free SysLog.zip](https://github.com/user-attachments/files/17067824/Free.SysLog.zip)

**Comment by trparky** [comment] 2024-09-19 23:30
No, I've not looked into the server stop/start issue yet. One issue at a time please.

**Comment by trparky** [comment] 2024-09-20 02:34
Good God! After almost two and a half hours playing in RegexMagic and RegexBuddy to develope my own parsing regex pattern, I think I finally have it nailed down.
[Free SysLog.zip](https://github.com/user-attachments/files/17069109/Free.SysLog.zip)

**Comment by trparky** [comment] 2024-09-20 03:17
[Free SysLog.zip](https://github.com/user-attachments/files/17069338/Free.SysLog.zip)
I have a new binary for you, it has some minor improvements.

**Comment by trparky** [comment] 2024-09-21 00:09
[Free SysLog.zip](https://github.com/user-attachments/files/17081781/Free.SysLog.zip)
Another new file to test with.

**Comment by trparky** [comment] 2024-09-21 20:49
And I have another test version for you, this time implementing a fix for the TCP server not closing out properly.
[Free SysLog.zip](https://github.com/user-attachments/files/17085687/Free.SysLog.zip)

**Comment by Alan-Carr** [comment] 2024-09-22 21:03
Log content would appear to have multiple entries eg Log is not split to individual records based on timestamps / lengths, furthermore server time would appear to be coming from a different log entry.

![image](https://github.com/user-attachments/assets/b9032c19-913d-4e5d-b625-e17895049f10)

There is an extra port being opened ?, furthermore yon can stop service and restart this leads to multiple copies of the previous ports.

**Comment by trparky** [comment] 2024-09-22 21:13
The problem is that I have nothing on my internal network that generates log examples like what you have so I have to create examples that I think are similar to yours.

My hardware doesn't generate timestamps like yours, they generate timestamps with month names in them.

Oh well, back to debugging.

**Comment by trparky** [comment] 2024-09-23 01:51
OK, I'm testing with the current log string...
<13>1 2024-09-22T21:42:52.690Z - RT-AX5400 dropbear[25788]: Exit before auth from <192.168.1.110:50354>: (user 'myuser', 0 fails): Error reading: Connection reset by peer

It appears that it's similar in format to the log that's failing on your end however, it parses properly on my end.

**Comment by trparky** [comment] 2024-09-23 01:52
Unless I can get a redacted log string from your end that's failing to be parsed, I can't figure out where the parsing is failing.

**Comment by trparky** [comment] 2024-09-23 02:22
Nevermind, I think I know where it was dying in the code. I have another test version for you.
[Free SysLog.zip](https://github.com/user-attachments/files/17092208/Free.SysLog.zip)

**Comment by Alan-Carr** [comment] 2024-09-23 18:06
Log data is appearing in the log field and in the Remote Process field

**Comment by trparky** [comment] 2024-09-23 21:26
Can you give me a redacted example of something that's failing to be parsed properly on your system? Because on my system and my data source, it all works properly.

**Comment by Alan-Carr** [comment] 2024-09-24 14:03
Ok will do

**Comment by Alan-Carr** [comment] 2024-09-25 15:18
Would a wireshark pcap file help or is this all you need -:
<134>1 2024-09-25T13:09:11.763Z - Cerebrum_Server 9036 auditApplication [audit@5353 subItem1="" subItem2="" subItem3="0" subItem4=""] Active Directory: DNS lookup completed in 0ms

**Comment by trparky** [comment] 2024-09-26 18:43
OK, I see what's going on. According to RFC standards, that log entry is technically in violation of the standards. How? Because there's no ":" (colon) after the "9036 auditApplication" to act as a delimiter between it and the rest of the log. That's why "9036 auditApplication [audit@5353 subItem1="" subItem2="" subItem3="0" subItem4=""] Active Directory:" ends up being part of the appname field because it ends with a ":".

**Comment by trparky** [comment] 2024-09-29 02:16
Never mind, with a lot of experimentation and some playing around with the rfc5424Regex, I've been able to fix the parsing of log entries that adhere to RFC standards as well as log entries that don't strictly adhere to RFC standards much like your example. The changes can be found in https://github.com/trparky/Free-SysLog/commit/18db28a2afa4e01724449f43cd78bebebadfc392.

Here is a new binary to test with.
[Free SysLog.zip](https://github.com/user-attachments/files/17177304/Free.SysLog.zip)

**Comment by Alan-Carr** [comment] 2024-09-30 08:37
Looking good

With regards to the missing ":" would you be able to point me where in the RFC this is mentioned ? 

With regards to the column headings -:

PRI VERSION SP TIMESTAMP SP HOSTNAME  SP APP-NAME SP PROCID SP MSGID

(SP is Space)

I don't think your showing the "PROCID"

**Comment by Alan-Carr** [comment] 2024-09-30 09:34
Can you check what ports your application is opening ?

Useful app https://www.nirsoft.net/utils/cports.html

**Comment by trparky** [comment] 2024-09-30 14:39
The message ID should be part of the message portion of the log entry. At least, that's how I see it.

As for the ports that the program is using, you can configure that in the program's settings.

**Comment by Alan-Carr** [comment] 2024-09-30 14:57
I think you may have some additional ports being opened

It was "PROCID" 

Are you able to point me to the ":" in the RFC ?

**Comment by trparky** [comment] 2024-09-30 15:55
https://datatracker.ietf.org/doc/html/rfc5424#section-6.5

**Comment by Alan-Carr** [comment] 2024-10-01 07:40
Looking at the structured data example -:

           <165>1 2003-10-11T22:14:15.003Z mymachine.example.com
           evntslog - ID47 [exampleSDID@32473 iut="3" eventSource=
           "Application" eventID="1011"] BOMAn application
           event log entry...

I can't see any ":" other than the date / time

Were you able to look at the opened ports ? / PROCID ?

**Comment by trparky** [comment] 2024-10-01 15:59
What about ports? Are you seeing open ports for anything other than what's
configured in the program's settings?
--
Thomas

**Comment by Alan-Carr** [comment] 2024-10-01 18:33
Yes I am 

In addition I'm also seen 2 ports for both UDP and TCP eg 4 in total but this maybe by design.

**Comment by trparky** [comment] 2024-10-02 00:05
Yes, that's by design. The program opens two TCP and two UDP ports; two (TCP and UDP) for IPv4 and two (TCP and UDP) for IPv6.

**Comment by trparky** [comment] 2024-10-02 00:22
I have a new test version that will allow you to disable IPv6 support if you so choose to do so.
[Free SysLog.zip](https://github.com/user-attachments/files/17218377/Free.SysLog.zip)

**Comment by Alan-Carr** [comment] 2024-10-02 07:56
Disabling IP6 seems to work and shows  only 2 ports as expected
Stopping server doesn't appear to work anymore (Server still running in task manager)
I'm still seeing the additional  tcp port making 3 assuming  IP6  disabled

**Comment by trparky** [comment] 2024-10-03 00:34
OK, I fixed it.
[Free SysLog.zip](https://github.com/user-attachments/files/17237707/Free.SysLog.zip)

**Comment by Alan-Carr** [comment] 2024-10-03 12:46
I wasn't sure whether you fixed the stopping of the server or the tcp port which remains open after you stop the server.

**Comment by trparky** [comment] 2024-10-03 12:51
I fixed the IPv6 disable code.
—
Thomas Parkison

**Comment by Alan-Carr** [comment] 2024-10-03 12:56
Do you think you will be able to fix the extra TCP port ?

**Comment by trparky** [comment] 2024-10-03 17:37
The extra port should only be there if you enable IPv6 support.

**Comment by Alan-Carr** [comment] 2024-10-04 10:07
This is not the case suggest you run the currports utility I previously suggested

**Comment by trparky** [comment] 2024-10-04 11:47
This is what I see on my own system...
![image](https://github.com/user-attachments/assets/75a8281f-f92d-447f-b86e-8e30c53e5107)
Again, this is normal when IPv6 support is enabled. Two ports for TCP on both IPv4 and IPv6 along with two ports for UDP on both IPv4 and IPv6. Again, normal operation.

**Comment by trparky** [comment] 2024-10-04 11:49
When I disable IPv6 support, this is what it looks like...
![image](https://github.com/user-attachments/assets/a0352b7d-97d0-4e55-99ba-e5190943ab5a)
One port for UDP and one port for TCP. Completely normal.

**Comment by Alan-Carr** [comment] 2024-10-04 13:04
I see an additional TCP port from you app local port 60155

**Comment by trparky** [comment] 2024-10-04 19:19
I have no code in the program that would open that port.

**Comment by trparky** [comment] 2024-10-10 23:59
Lots of changes and tweaks including a rate limiter on alerts.
[Free SysLog.zip](https://github.com/user-attachments/files/17335466/Free.SysLog.zip)

**Comment by trparky** [comment] 2024-10-12 11:41
Closing issue as solved.

**Closed as completed by trparky** 2024-10-12 11:41 UTC

**Comment by trparky** [comment] 2024-10-12 23:14
Due to a bug, you will not be able to update automatically. Please download the latest release from this GitHub repo.
